export const REFERENCE_ACADEMIC_YEAR = 2026

export const SOURCE_DIRECTORY = '2026 初期データー　ベータ版'

export const SOURCE_FILES = {
  undergraduate2026: 'summary_2026.pdf',
  undergraduate2025: 'summary_2025.pdf',
  undergraduateChanges2025: 'summary_change_2025_0325.pdf',
  undergraduateBefore2025: 'summary_2024.pdf',
  graduate2026: 'summary_graduate_2026.pdf',
  graduate2025: 'summary_graduate_2025.pdf',
  graduateChanges2025: 'summary_graduate_change_2025.pdf',
  graduateBefore2025: 'summary_graduate_2024.pdf',
  offerings2026: 'syllabus_analysis_2026.xlsx',
}

export const SUPPLEMENTAL_SOURCE_FILES = {
  syllabusUrls2026: '授業一覧.csv',
}

export const SELECTABLE_COURSE_TAGS = [
  'レポート・課題重視',
  'レポート・課題あり',
  '試験あり',
  '試験重視',
  '試験なし',
  '態度点なし',
  '態度点低め',
  '態度点高め',
  'オンデマンド多め',
  'オンデマンド少なめ',
  'オンデマンドなし',
  '全てオンデマンド',
  '前提履修なし',
  '前提履修あり',
  'グループワークなし',
  'グループワークあり',
  '情報・数理',
  'プログラミング・システム',
  'AI・データ',
  '心理・認知',
  '社会・ビジネス',
  '語学・コミュニケーション',
  'メディア・デザイン',
  '健康・スポーツ',
  'キャリア・教養',
  'その他',
]

const undergraduate = ({
  code,
  faculty,
  department = null,
  major = null,
  validCurrentYears2026,
  campus = '長久手キャンパス',
  aliases = [],
  admissionOrganizationOverrides = [],
}) => ({
  code,
  studentLevel: 'undergraduate',
  studentType: 'U',
  programLevel: 'undergraduate',
  faculty,
  graduateSchool: null,
  department,
  major,
  course: null,
  specialization: null,
  campus,
  validCurrentYears2026,
  aliases,
  admissionOrganizationOverrides,
})

const graduate = ({
  code,
  graduateSchool,
  department = null,
  major = null,
  course = null,
  specialization = null,
  campus = '長久手キャンパス',
  aliases = [],
}) => {
  const studentType = code.at(-1)
  return {
    code,
    studentLevel: 'graduate',
    studentType,
    programLevel: studentType === 'D' ? 'doctoral_latter' : 'masters_or_doctoral_first',
    faculty: null,
    graduateSchool,
    department,
    major,
    course,
    specialization,
    campus,
    validCurrentYears2026: studentType === 'D' ? [1, 2, 3] : [1, 2],
    aliases,
  }
}

export const STUDENT_ORGANIZATIONS = [
  undergraduate({
    code: 'LJU',
    faculty: '文学部',
    department: '国文学科',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'LCU',
    faculty: '文学部',
    department: '総合英語学科',
    validCurrentYears2026: [3, 4],
  }),
  undergraduate({
    code: 'LAU',
    faculty: '文学部',
    department: '教育学科',
    validCurrentYears2026: [3, 4],
    aliases: ['旧・文学部 教育学科'],
  }),
  undergraduate({
    code: 'KEU',
    faculty: '教育学部',
    department: '教育学科',
    validCurrentYears2026: [1, 2],
  }),
  undergraduate({
    code: 'NKU',
    faculty: '人間情報学部',
    department: '人間情報学科',
    major: '感性工学専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'NDU',
    faculty: '人間情報学部',
    department: '人間情報学科',
    major: 'データサイエンス専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'NMU',
    faculty: '人間情報学部',
    department: '人間情報学科',
    major: '数学・情報教員養成専攻',
    validCurrentYears2026: [1],
  }),
  undergraduate({
    code: 'PFU',
    faculty: '心理学部',
    department: '心理学科',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'CSU',
    faculty: '創造表現学部',
    department: '創造表現学科',
    major: '創作表現専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'CMU',
    faculty: '創造表現学部',
    department: '創造表現学科',
    major: 'メディアプロデュース専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'CKU',
    faculty: '創造表現学部',
    department: '創造表現学科',
    major: '建築・インテリアデザイン専攻',
    validCurrentYears2026: [3, 4],
    aliases: ['旧・建築・インテリアデザイン専攻'],
  }),
  undergraduate({
    code: 'AAU',
    faculty: '建築学部',
    department: '建築学科',
    major: '建築・まちづくり専攻',
    validCurrentYears2026: [1, 2],
  }),
  undergraduate({
    code: 'ARU',
    faculty: '建築学部',
    department: '建築学科',
    major: '住居・インテリアデザイン専攻',
    validCurrentYears2026: [1, 2],
  }),
  undergraduate({
    code: 'HCU',
    faculty: '健康医療科学部',
    department: '医療貢献学科',
    major: '言語聴覚学専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'HVU',
    faculty: '健康医療科学部',
    department: '医療貢献学科',
    major: '視覚科学専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'HPU',
    faculty: '健康医療科学部',
    department: '医療貢献学科',
    major: '理学療法学専攻',
    validCurrentYears2026: [1, 2, 3],
  }),
  undergraduate({
    code: 'HMU',
    faculty: '健康医療科学部',
    department: '医療貢献学科',
    major: '臨床検査学専攻',
    validCurrentYears2026: [1, 2, 3],
  }),
  undergraduate({
    code: 'HHU',
    faculty: '健康医療科学部',
    department: 'スポーツ・健康医科学科',
    major: 'スポーツ・健康科学専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'HAU',
    faculty: '健康医療科学部',
    department: 'スポーツ・健康医科学科',
    major: '救急救命学専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'HEU',
    faculty: '健康医療科学部',
    department: '健康栄養学科',
    validCurrentYears2026: [4],
    aliases: ['旧・健康栄養学科'],
  }),
  undergraduate({
    code: 'SEU',
    faculty: '食健康科学部',
    department: '健康栄養学科',
    validCurrentYears2026: [1, 2, 3],
  }),
  undergraduate({
    code: 'SFU',
    faculty: '食健康科学部',
    department: '食創造科学科',
    validCurrentYears2026: [1, 2, 3],
  }),
  undergraduate({
    code: 'FSU',
    faculty: '福祉貢献学部',
    department: '福祉貢献学科',
    major: '社会福祉専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'FCU',
    faculty: '福祉貢献学部',
    department: '福祉貢献学科',
    major: '子ども福祉専攻',
    validCurrentYears2026: [1, 2, 3, 4],
  }),
  undergraduate({
    code: 'GLU',
    faculty: '交流文化学部',
    department: '交流文化学科',
    major: 'ランゲージ専攻',
    validCurrentYears2026: [1, 2, 3, 4],
    campus: '星が丘キャンパス',
  }),
  undergraduate({
    code: 'GMU',
    faculty: '交流文化学部',
    department: '交流文化学科',
    major: '国際交流・観光専攻',
    validCurrentYears2026: [1, 2, 3, 4],
    campus: '星が丘キャンパス',
    aliases: ['観光専攻'],
    admissionOrganizationOverrides: [
      { admissionYearFrom: 2026, admissionYearTo: 2026, major: '観光専攻' },
    ],
  }),
  undergraduate({
    code: 'VBU',
    faculty: 'ビジネス学部',
    department: 'ビジネス学科',
    validCurrentYears2026: [1, 2, 3, 4],
    campus: '星が丘キャンパス',
  }),
  undergraduate({
    code: 'EXU',
    faculty: 'グローバル・コミュニケーション学部',
    validCurrentYears2026: [1, 2, 3, 4],
    campus: '星が丘キャンパス',
  }),

  graduate({
    code: 'AJM',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '国文学専修',
  }),
  graduate({
    code: 'AJD',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '国文学専修',
  }),
  graduate({
    code: 'ALM',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '図書館情報学専修',
  }),
  graduate({
    code: 'ALD',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '図書館情報学専修',
  }),
  graduate({
    code: 'ADM',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '情報デザイン・システム専修',
  }),
  graduate({
    code: 'ADD',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '情報デザイン・システム専修',
  }),
  graduate({
    code: 'ASM',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '創作表現専修',
  }),
  graduate({
    code: 'ASD',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '創作表現専修',
  }),
  graduate({
    code: 'AMM',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: 'メディアプロデュース専修',
  }),
  graduate({
    code: 'AMD',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: 'メディアプロデュース専修',
  }),
  graduate({
    code: 'AKM',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '建築・インテリアデザイン専修',
  }),
  graduate({
    code: 'AKD',
    graduateSchool: '文化創造研究科',
    department: '文化創造専攻',
    specialization: '建築・インテリアデザイン専修',
  }),
  graduate({
    code: 'CLD',
    graduateSchool: null,
    department: null,
    specialization: '図書館情報学領域',
    aliases: ['正式な研究科階層は資料内で一意に確認できず'],
  }),
  graduate({
    code: 'DAM',
    graduateSchool: '教育学研究科',
    department: '発達教育専攻',
    specialization: '教育学専修',
  }),
  graduate({
    code: 'DCM',
    graduateSchool: '教育学研究科',
    department: '発達教育専攻',
    specialization: '子ども発達専修',
  }),
  graduate({
    code: 'FPM',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '心理学専修',
  }),
  graduate({
    code: 'FPD',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '心理学専修',
  }),
  graduate({
    code: 'FRM',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '臨床心理学専修',
  }),
  graduate({
    code: 'FRD',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '臨床心理学専修',
  }),
  graduate({
    code: 'FSM',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '社会福祉学専修',
  }),
  graduate({
    code: 'FSD',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '社会福祉学専修',
  }),
  graduate({
    code: 'FCM',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '言語聴覚学専修',
  }),
  graduate({
    code: 'FCD',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '言語聴覚学専修',
  }),
  graduate({
    code: 'FVM',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '視覚科学専修',
  }),
  graduate({
    code: 'FVD',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: '視覚科学専修',
  }),
  graduate({
    code: 'FHM',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: 'スポーツ・健康医科学専修',
  }),
  graduate({
    code: 'FHD',
    graduateSchool: '心理医療科学研究科',
    department: '心理医療科学専攻',
    specialization: 'スポーツ・健康医科学専修',
  }),
  graduate({ code: 'HNM', graduateSchool: '健康栄養科学研究科', department: '健康栄養科学専攻' }),
  graduate({
    code: 'JLM',
    graduateSchool: 'グローバルカルチャー・コミュニケーション研究科',
    department: 'グローバルカルチャー・コミュニケーション専攻',
    course: '言語文化コース',
    campus: '星が丘キャンパス',
  }),
  graduate({
    code: 'JLD',
    graduateSchool: 'グローバルカルチャー・コミュニケーション研究科',
    department: 'グローバルカルチャー・コミュニケーション専攻',
    course: '言語文化コース',
    campus: '星が丘キャンパス',
  }),
  graduate({
    code: 'JGM',
    graduateSchool: 'グローバルカルチャー・コミュニケーション研究科',
    department: 'グローバルカルチャー・コミュニケーション専攻',
    course: '交流文化コース',
    campus: '星が丘キャンパス',
  }),
  graduate({
    code: 'JGD',
    graduateSchool: 'グローバルカルチャー・コミュニケーション研究科',
    department: 'グローバルカルチャー・コミュニケーション専攻',
    course: '交流文化コース',
    campus: '星が丘キャンパス',
  }),
  graduate({
    code: 'KAM',
    graduateSchool: 'ビジネス研究科',
    department: 'ビジネス専攻',
    specialization: 'アカウンティング専修',
    campus: '星が丘キャンパス',
  }),
  graduate({
    code: 'KAD',
    graduateSchool: 'ビジネス研究科',
    department: 'ビジネス専攻',
    specialization: 'アカウンティング専修',
    campus: '星が丘キャンパス',
  }),
  graduate({
    code: 'KMM',
    graduateSchool: 'ビジネス研究科',
    department: 'ビジネス専攻',
    specialization: 'マネジメント＆エコノミー専修',
    campus: '星が丘キャンパス',
  }),
  graduate({
    code: 'KMD',
    graduateSchool: 'ビジネス研究科',
    department: 'ビジネス専攻',
    specialization: 'マネジメント＆エコノミー専修',
    campus: '星が丘キャンパス',
  }),
]

export const UNDERGRADUATE_CODES = STUDENT_ORGANIZATIONS.filter(
  (organization) => organization.studentLevel === 'undergraduate',
).map((organization) => organization.code)

export const CONTEXT_MARKERS = [
  ['数学・情報教員養成専攻', ['NMU']],
  ['データサイエンス専攻', ['NDU']],
  ['感性工学専攻', ['NKU']],
  ['建築・まちづくり専攻', ['AAU']],
  ['住居・インテリアデザイン専攻', ['ARU']],
  ['インテリアデザイン専攻', ['ARU']],
  ['建築・インテリアデザイン専攻', ['CKU']],
  ['メディアプロデュース専攻', ['CMU']],
  ['創作表現専攻', ['CSU']],
  ['言語聴覚学専攻', ['HCU', 'FCM', 'FCD']],
  ['視覚科学専攻', ['HVU', 'FVM', 'FVD']],
  ['理学療法学専攻', ['HPU']],
  ['臨床検査学専攻', ['HMU']],
  ['スポーツ・健康医科学専修', ['FHM', 'FHD']],
  ['スポーツ・健康科学専攻', ['HHU']],
  ['救急救命学専攻', ['HAU']],
  ['健康栄養科学専攻', ['HNM']],
  ['健康栄養学科', ['SEU', 'HEU']],
  ['食創造科学科', ['SFU']],
  ['社会福祉専攻', ['FSU']],
  ['子ども福祉専攻', ['FCU']],
  ['ランゲージ専攻', ['GLU']],
  ['国際交流・観光専攻', ['GMU']],
  ['観光専攻', ['GMU']],
  ['国文学専修', ['AJM', 'AJD']],
  ['図書館情報学専修', ['ALM', 'ALD']],
  ['情報デザイン・システム専修', ['ADM', 'ADD']],
  ['創作表現専修', ['ASM', 'ASD']],
  ['メディアプロデュース専修', ['AMM', 'AMD']],
  ['建築・インテリアデザイン専修', ['AKM', 'AKD']],
  ['教育学専修', ['DAM']],
  ['子ども発達専修', ['DCM']],
  ['心理学専修', ['FPM', 'FPD']],
  ['臨床心理学専修', ['FRM', 'FRD']],
  ['社会福祉学専修', ['FSM', 'FSD']],
  ['言語文化コース', ['JLM', 'JLD']],
  ['交流文化コース', ['JGM', 'JGD']],
  ['アカウンティング専修', ['KAM', 'KAD']],
  ['マネジメント＆エコノミー専修', ['KMM', 'KMD']],
  ['国文学科', ['LJU']],
  ['総合英語学科', ['LCU']],
  ['心理学科', ['PFU']],
  ['ビジネス学科', ['VBU']],
  ['グローバル・コミュニケーション学部', ['EXU']],
]

export const FACULTY_CODE_GROUPS = Object.groupBy(
  STUDENT_ORGANIZATIONS.filter((organization) => organization.studentLevel === 'undergraduate'),
  (organization) => organization.faculty,
)

export const DEPARTMENT_CODE_GROUPS = Object.groupBy(
  STUDENT_ORGANIZATIONS.filter(
    (organization) => organization.studentLevel === 'undergraduate' && organization.department,
  ),
  (organization) => `${organization.faculty}\u0000${organization.department}`,
)
